#!/usr/bin/env python3
"""Classify the local Klein four generated by deck and kernel involutions."""

import json
from collections import Counter, deque
from itertools import combinations
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

GRAPH_SOURCE = (
    ROOT
    / "sources"
    / "native_g30_graph_input_001.json"
)

ANATOMY_SOURCE = (
    ROOT
    / "artifacts"
    / "json"
    / "native_g30_group_anatomy_002.json"
)

KERNEL_SOURCE = (
    ROOT
    / "artifacts"
    / "json"
    / "native_g30_triangle_kernel_involution_012.json"
)

OUTPUT = (
    ROOT
    / "artifacts"
    / "json"
    / "native_g30_local_klein_four_013.json"
)


def compose(left, right):
    return tuple(
        left[right[index]]
        for index in range(len(left))
    )


def permutation_order(permutation):
    identity = tuple(range(len(permutation)))
    current = identity
    order = 0

    while True:
        order += 1
        current = compose(permutation, current)

        if current == identity:
            return order


def permutation_cycles(permutation):
    unseen = set(range(len(permutation)))
    cycles = []

    while unseen:
        start = min(unseen)
        current = start
        cycle = []

        while current in unseen:
            unseen.remove(current)
            cycle.append(current)
            current = permutation[current]

        cycles.append(tuple(cycle))

    return tuple(sorted(
        cycles,
        key=lambda cycle: (
            len(cycle),
            cycle,
        ),
    ))


def image_of_subset(subset, permutation):
    return tuple(sorted(
        permutation[vertex]
        for vertex in subset
    ))


def triangle_set(vertices, edges):
    edge_set = frozenset(
        tuple(sorted(edge))
        for edge in edges
    )

    return tuple(sorted(
        triple
        for triple in combinations(vertices, 3)
        if all(
            tuple(sorted(edge)) in edge_set
            for edge in combinations(triple, 2)
        )
    ))


def component_sizes(vertices, edges):
    adjacency = {
        vertex: set()
        for vertex in vertices
    }

    for left, right in edges:
        adjacency[left].add(right)
        adjacency[right].add(left)

    unseen = set(vertices)
    sizes = []

    while unseen:
        start = min(unseen)
        unseen.remove(start)
        queue = deque([start])
        size = 0

        while queue:
            current = queue.popleft()
            size += 1

            for neighbor in adjacency[current]:
                if neighbor not in unseen:
                    continue

                unseen.remove(neighbor)
                queue.append(neighbor)

        sizes.append(size)

    return tuple(sorted(sizes, reverse=True))


def element_anatomy(
    label,
    element,
    vertices,
    edges,
    triangles,
):
    cycles = permutation_cycles(element)

    fixed_vertices = tuple(
        cycle[0]
        for cycle in cycles
        if len(cycle) == 1
    )

    fixed_vertex_set = frozenset(fixed_vertices)

    fixed_edges = tuple(
        edge
        for edge in edges
        if edge[0] in fixed_vertex_set
        and edge[1] in fixed_vertex_set
    )

    pointwise_fixed_triangles = tuple(
        triangle
        for triangle in triangles
        if all(
            element[vertex] == vertex
            for vertex in triangle
        )
    )

    setwise_fixed_triangles = tuple(
        triangle
        for triangle in triangles
        if image_of_subset(triangle, element) == triangle
    )

    triangle_orbits = []
    unseen = set(triangles)

    while unseen:
        triangle = min(unseen)
        image = image_of_subset(triangle, element)
        orbit = tuple(sorted({
            triangle,
            image,
        }))

        triangle_orbits.append(orbit)
        unseen -= set(orbit)

    return {
        "label": label,
        "permutation": list(element),
        "order": permutation_order(element),
        "cycle_length_profile": {
            str(length): count
            for length, count in sorted(
                Counter(
                    len(cycle)
                    for cycle in cycles
                ).items()
            )
        },
        "fixed_vertex_count": len(fixed_vertices),
        "fixed_vertices": list(fixed_vertices),
        "transposition_count": sum(
            1
            for cycle in cycles
            if len(cycle) == 2
        ),
        "fixed_edge_count": len(fixed_edges),
        "fixed_edges": [
            list(edge)
            for edge in fixed_edges
        ],
        "fixed_subgraph_component_sizes": list(
            component_sizes(
                fixed_vertices,
                fixed_edges,
            )
        ),
        "pointwise_fixed_triangle_count": len(
            pointwise_fixed_triangles
        ),
        "pointwise_fixed_triangles": [
            list(triangle)
            for triangle in pointwise_fixed_triangles
        ],
        "setwise_fixed_triangle_count": len(
            setwise_fixed_triangles
        ),
        "setwise_fixed_triangles": [
            list(triangle)
            for triangle in setwise_fixed_triangles
        ],
        "triangle_orbit_size_profile": {
            str(size): count
            for size, count in sorted(
                Counter(
                    len(orbit)
                    for orbit in triangle_orbits
                ).items()
            )
        },
    }


def main():
    graph_source = json.loads(GRAPH_SOURCE.read_text())
    anatomy_source = json.loads(ANATOMY_SOURCE.read_text())
    kernel_source = json.loads(KERNEL_SOURCE.read_text())

    vertices = tuple(graph_source["vertices"])
    edges = tuple(
        tuple(sorted(edge))
        for edge in graph_source["edges"]
    )

    triangles = triangle_set(vertices, edges)

    identity = tuple(range(len(vertices)))

    deck = next(
        tuple(element)
        for element in anatomy_source["center"]
        if tuple(element) != identity
    )

    kernel = tuple(
        kernel_source["kernel_involution"]
    )

    product = compose(deck, kernel)

    klein_four = frozenset({
        identity,
        deck,
        kernel,
        product,
    })

    nonidentity_rows = [
        element_anatomy(
            "central_deck",
            deck,
            vertices,
            edges,
            triangles,
        ),
        element_anatomy(
            "triangle_kernel",
            kernel,
            vertices,
            edges,
            triangles,
        ),
        element_anatomy(
            "deck_times_kernel",
            product,
            vertices,
            edges,
            triangles,
        ),
    ]

    fixed_vertex_profiles = Counter(
        row["fixed_vertex_count"]
        for row in nonidentity_rows
    )

    fixed_triangle_profiles = Counter(
        row["setwise_fixed_triangle_count"]
        for row in nonidentity_rows
    )

    common_fixed_vertices = set(vertices)

    for element in (deck, kernel, product):
        common_fixed_vertices &= {
            vertex
            for vertex in vertices
            if element[vertex] == vertex
        }

    vertex_orbits = []
    unseen_vertices = set(vertices)

    while unseen_vertices:
        vertex = min(unseen_vertices)

        orbit = frozenset(
            element[vertex]
            for element in klein_four
        )

        vertex_orbits.append(tuple(sorted(orbit)))
        unseen_vertices -= set(orbit)

    vertex_orbits = tuple(sorted(vertex_orbits))

    vertex_orbit_size_profile = Counter(
        len(orbit)
        for orbit in vertex_orbits
    )

    triangle_orbits = []
    unseen_triangles = set(triangles)

    while unseen_triangles:
        triangle = min(unseen_triangles)

        orbit = frozenset(
            image_of_subset(triangle, element)
            for element in klein_four
        )

        triangle_orbits.append(tuple(sorted(orbit)))
        unseen_triangles -= set(orbit)

    triangle_orbits = tuple(sorted(triangle_orbits))

    triangle_orbit_size_profile = Counter(
        len(orbit)
        for orbit in triangle_orbits
    )

    checks = {
        "source_kernel_audit_pass": (
            kernel_source["audit_pass"]
        ),
        "klein_four_order_is_4": (
            len(klein_four) == 4
        ),
        "all_nonidentity_elements_have_order_2": all(
            row["order"] == 2
            for row in nonidentity_rows
        ),
        "deck_and_kernel_commute": (
            compose(deck, kernel)
            == compose(kernel, deck)
        ),
        "deck_is_fixed_point_free": (
            nonidentity_rows[0]["fixed_vertex_count"] == 0
        ),
        "kernel_has_six_fixed_vertices": (
            nonidentity_rows[1]["fixed_vertex_count"] == 6
        ),
        "product_is_fixed_point_free": (
            nonidentity_rows[2]["fixed_vertex_count"] == 0
        ),
        "kernel_is_unique_fixed_point_bearing_involution": (
            fixed_vertex_profiles == {0: 2, 6: 1}
        ),
        "kernel_is_unique_triangle_fixing_involution": (
            fixed_triangle_profiles == {0: 2, 8: 1}
        ),
        "no_vertex_fixed_by_full_klein_four": (
            len(common_fixed_vertices) == 0
        ),
        "vertex_orbits_account_for_30_vertices": (
            sum(
                size * count
                for size, count
                in vertex_orbit_size_profile.items()
            )
            == 30
        ),
        "triangle_orbits_account_for_20_triangles": (
            sum(
                size * count
                for size, count
                in triangle_orbit_size_profile.items()
            )
            == 20
        ),
    }

    payload = {
        "certificate_id": (
            "native_g30_local_klein_four_013"
        ),
        "graph_source": str(
            GRAPH_SOURCE.relative_to(ROOT)
        ),
        "anatomy_source": str(
            ANATOMY_SOURCE.relative_to(ROOT)
        ),
        "kernel_source": str(
            KERNEL_SOURCE.relative_to(ROOT)
        ),
        "klein_four_order": len(klein_four),
        "elements": [
            list(element)
            for element in sorted(klein_four)
        ],
        "nonidentity_element_anatomy": (
            nonidentity_rows
        ),
        "fixed_vertex_count_profile": {
            str(count): multiplicity
            for count, multiplicity in sorted(
                fixed_vertex_profiles.items()
            )
        },
        "setwise_fixed_triangle_count_profile": {
            str(count): multiplicity
            for count, multiplicity in sorted(
                fixed_triangle_profiles.items()
            )
        },
        "common_fixed_vertex_count": len(
            common_fixed_vertices
        ),
        "common_fixed_vertices": sorted(
            common_fixed_vertices
        ),
        "vertex_orbit_count": len(vertex_orbits),
        "vertex_orbit_size_profile": {
            str(size): count
            for size, count in sorted(
                vertex_orbit_size_profile.items()
            )
        },
        "vertex_orbits": [
            list(orbit)
            for orbit in vertex_orbits
        ],
        "triangle_orbit_count": len(
            triangle_orbits
        ),
        "triangle_orbit_size_profile": {
            str(size): count
            for size, count in sorted(
                triangle_orbit_size_profile.items()
            )
        },
        "triangle_orbits": [
            [
                list(triangle)
                for triangle in orbit
            ]
            for orbit in triangle_orbits
        ],
        "classification_result": (
            "The central deck involution and the hidden "
            "triangle-kernel involution generate a Klein four. "
            "The triangle-kernel element is the unique "
            "fixed-point-bearing involution: it fixes six "
            "vertices and eight triangles. The deck element and "
            "their product are both fixed-point-free and fix no "
            "triangle. The full Klein four has no globally fixed "
            "vertex."
        ),
        "checks": checks,
        "audit_pass": all(checks.values()),
        "boundary": {
            "local_klein_four_classified": True,
            "three_involution_profiles_recorded": True,
            "klein_four_geometric_name_open": True,
            "relation_to_vertex_stabilizer_v4_mixed_open": True,
            "physical_claim": False,
        },
    }

    OUTPUT.write_text(
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )

    print("OUT ==")
    print("output:", OUTPUT)
    print("audit_pass:", payload["audit_pass"])
    print(
        "klein_four_order:",
        payload["klein_four_order"],
    )
    print(
        "fixed_vertex_count_profile:",
        payload["fixed_vertex_count_profile"],
    )
    print(
        "setwise_fixed_triangle_count_profile:",
        payload[
            "setwise_fixed_triangle_count_profile"
        ],
    )
    print(
        "common_fixed_vertex_count:",
        payload["common_fixed_vertex_count"],
    )
    print(
        "vertex_orbit_size_profile:",
        payload["vertex_orbit_size_profile"],
    )
    print(
        "triangle_orbit_size_profile:",
        payload["triangle_orbit_size_profile"],
    )

    for row in nonidentity_rows:
        print(
            row["label"],
            "fixed_vertices:",
            row["fixed_vertex_count"],
            "fixed_triangles:",
            row["setwise_fixed_triangle_count"],
            "fixed_components:",
            row["fixed_subgraph_component_sizes"],
        )

    print(
        "classification_result:",
        payload["classification_result"],
    )


if __name__ == "__main__":
    main()
