#!/usr/bin/env python3
"""Classify the order-8 subgroup generated by the two Klein fours."""

import json
from collections import Counter, deque
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

COMPARISON_SOURCE = (
    ROOT
    / "artifacts"
    / "json"
    / "native_g30_klein_four_comparison_014.json"
)

OUTPUT = (
    ROOT
    / "artifacts"
    / "json"
    / "native_g30_generated_order8_subgroup_015.json"
)


def compose(left, right):
    return tuple(
        left[right[index]]
        for index in range(len(left))
    )


def inverse(permutation):
    result = [0] * len(permutation)

    for source, target in enumerate(permutation):
        result[target] = source

    return tuple(result)


def generated_subgroup(generators, identity):
    expanded = set(generators)

    expanded.update(
        inverse(generator)
        for generator in generators
    )

    subgroup = {identity}
    queue = deque([identity])

    while queue:
        current = queue.popleft()

        for generator in expanded:
            product = compose(generator, current)

            if product in subgroup:
                continue

            subgroup.add(product)
            queue.append(product)

    return frozenset(subgroup)


def permutation_order(permutation):
    identity = tuple(range(len(permutation)))
    current = identity
    order = 0

    while True:
        order += 1
        current = compose(permutation, current)

        if current == identity:
            return order


def commutator(left, right):
    return compose(
        compose(
            compose(
                inverse(left),
                inverse(right),
            ),
            left,
        ),
        right,
    )


def main():
    source = json.loads(COMPARISON_SOURCE.read_text())

    local_v4 = frozenset(
        tuple(element)
        for element in source[
            "local_triangle_klein_four"
        ]["elements"]
    )

    vertex_v4 = frozenset(
        tuple(element)
        for element in source[
            "vertex_stabilizer_v4_mixed"
        ]["elements"]
    )

    degree = len(next(iter(local_v4)))
    identity = tuple(range(degree))

    group = generated_subgroup(
        tuple(local_v4 | vertex_v4),
        identity,
    )

    order_profile = Counter(
        permutation_order(element)
        for element in group
    )

    group_center = frozenset(
        element
        for element in group
        if all(
            compose(element, other)
            == compose(other, element)
            for other in group
        )
    )

    commutators = {
        commutator(left, right)
        for left in group
        for right in group
    }

    derived = generated_subgroup(
        tuple(commutators),
        identity,
    )

    is_abelian = len(group_center) == len(group)

    if (
        len(group) == 8
        and dict(sorted(order_profile.items()))
        == {1: 1, 2: 7}
        and is_abelian
    ):
        abstract_type = "C2_x_C2_x_C2"
    elif (
        len(group) == 8
        and dict(sorted(order_profile.items()))
        == {1: 1, 2: 5, 4: 2}
        and not is_abelian
        and len(group_center) == 2
    ):
        abstract_type = "D8"
    elif (
        len(group) == 8
        and dict(sorted(order_profile.items()))
        == {1: 1, 2: 3, 4: 4}
        and is_abelian
    ):
        abstract_type = "C4_x_C2"
    elif (
        len(group) == 8
        and dict(sorted(order_profile.items()))
        == {1: 1, 2: 1, 4: 6}
        and not is_abelian
    ):
        abstract_type = "Q8"
    else:
        abstract_type = "unclassified"

    local_normal = all(
        compose(
            compose(carrier, element),
            inverse(carrier),
        )
        in local_v4
        for carrier in group
        for element in local_v4
    )

    vertex_normal = all(
        compose(
            compose(carrier, element),
            inverse(carrier),
        )
        in vertex_v4
        for carrier in group
        for element in vertex_v4
    )

    checks = {
        "source_audit_pass": source["audit_pass"],
        "generated_group_order_is_8": len(group) == 8,
        "abstract_type_classified": (
            abstract_type != "unclassified"
        ),
        "derived_subgroup_order_matches_abelianity": (
            len(derived) == 1
            if is_abelian
            else len(derived) > 1
        ),
        "local_v4_is_subgroup": (
            local_v4.issubset(group)
        ),
        "vertex_v4_is_subgroup": (
            vertex_v4.issubset(group)
        ),
        "intersection_order_is_2": (
            len(local_v4.intersection(vertex_v4)) == 2
        ),
    }

    payload = {
        "certificate_id": (
            "native_g30_generated_order8_subgroup_015"
        ),
        "source": str(
            COMPARISON_SOURCE.relative_to(ROOT)
        ),
        "group_order": len(group),
        "element_order_profile": {
            str(order): count
            for order, count in sorted(
                order_profile.items()
            )
        },
        "center_order": len(group_center),
        "derived_subgroup_order": len(derived),
        "abelian": is_abelian,
        "abstract_group_type": abstract_type,
        "local_klein_four_normal": local_normal,
        "vertex_stabilizer_v4_normal": vertex_normal,
        "local_vertex_v4_intersection_order": len(
            local_v4.intersection(vertex_v4)
        ),
        "elements": [
            list(element)
            for element in sorted(group)
        ],
        "classification_result": (
            "The subgroup generated by the triangle-local "
            "Klein four and the V4_mixed vertex stabilizer is "
            f"{abstract_type}."
        ),
        "checks": checks,
        "audit_pass": all(checks.values()),
        "boundary": {
            "generated_order8_group_identified": True,
            "subgroup_action_geometry_open": True,
            "physical_claim": False,
        },
    }

    OUTPUT.write_text(
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )

    print("OUT ==")
    print("output:", OUTPUT)
    print("audit_pass:", payload["audit_pass"])
    print("group_order:", payload["group_order"])
    print(
        "element_order_profile:",
        payload["element_order_profile"],
    )
    print("center_order:", payload["center_order"])
    print(
        "derived_subgroup_order:",
        payload["derived_subgroup_order"],
    )
    print("abelian:", payload["abelian"])
    print(
        "abstract_group_type:",
        payload["abstract_group_type"],
    )
    print(
        "local_klein_four_normal:",
        payload["local_klein_four_normal"],
    )
    print(
        "vertex_stabilizer_v4_normal:",
        payload["vertex_stabilizer_v4_normal"],
    )
    print(
        "classification_result:",
        payload["classification_result"],
    )


if __name__ == "__main__":
    main()
