#!/usr/bin/env python3
"""Compose the native G30 affine-cube geometry theorem package."""

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

SOURCE_PATHS = [
    ROOT / "artifacts/json/native_g30_generated_order8_subgroup_015.json",
    ROOT / "artifacts/json/native_g30_c2_cube_action_016.json",
    ROOT / "artifacts/json/native_g30_c2_cube_orbit_quotient_017.json",
    ROOT / "artifacts/json/native_g30_c2_orbit_skeleton_018.json",
    ROOT / "artifacts/json/native_g30_weighted_orbit_skeleton_019.json",
    ROOT / "artifacts/json/native_g30_c2_cube_normalizer_020.json",
    ROOT / "artifacts/json/native_g30_c2_cube_normalizer_group_021.json",
    ROOT / "artifacts/json/native_g30_c2_cube_linear_action_022.json",
    ROOT / "artifacts/json/native_g30_c2_cube_named_fixed_plane_023.json",
    ROOT / "artifacts/json/native_g30_c2_cube_involution_register_024.json",
    ROOT / "artifacts/json/native_g30_u_k_fixed_subgraph_comparison_025.json",
    ROOT / "artifacts/json/native_g30_c2_cube_conjugacy_census_026.json",
    ROOT / "artifacts/json/native_g30_fifteen_cube_graph_027.json",
    ROOT / "artifacts/json/native_g30_cube_triangle_centers_028.json",
    ROOT / "artifacts/json/native_g30_petersen_from_cube_centers_029.json",
]

OUTPUT = (
    ROOT
    / "artifacts/json/"
    "native_g30_cube_geometry_theorem_package_030.json"
)


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    sources = {
        path.stem: json.loads(path.read_text())
        for path in SOURCE_PATHS
    }

    source_receipts = [
        {
            "path": str(path.relative_to(ROOT)),
            "sha256": sha256(path),
            "certificate_id": sources[path.stem][
                "certificate_id"
            ],
            "audit_pass": sources[path.stem][
                "audit_pass"
            ],
        }
        for path in SOURCE_PATHS
    ]

    s015 = sources[
        "native_g30_generated_order8_subgroup_015"
    ]
    s020 = sources[
        "native_g30_c2_cube_normalizer_020"
    ]
    s021 = sources[
        "native_g30_c2_cube_normalizer_group_021"
    ]
    s022 = sources[
        "native_g30_c2_cube_linear_action_022"
    ]
    s023 = sources[
        "native_g30_c2_cube_named_fixed_plane_023"
    ]
    s024 = sources[
        "native_g30_c2_cube_involution_register_024"
    ]
    s026 = sources[
        "native_g30_c2_cube_conjugacy_census_026"
    ]
    s027 = sources[
        "native_g30_fifteen_cube_graph_027"
    ]
    s028 = sources[
        "native_g30_cube_triangle_centers_028"
    ]
    s029 = sources[
        "native_g30_petersen_from_cube_centers_029"
    ]

    theorem_statements = [
        {
            "theorem_id": "T030-1",
            "statement": (
                "The subgroup generated by the triangle-local "
                "Klein four and the V4_mixed vertex stabilizer "
                "is elementary abelian of order 8, hence "
                "isomorphic to C2^3."
            ),
            "evidence": [
                "native_g30_generated_order8_subgroup_015"
            ],
        },
        {
            "theorem_id": "T030-2",
            "statement": (
                "Its normalizer in Aut(G30) has order 16 and "
                "is explicitly isomorphic to D8 x C2."
            ),
            "evidence": [
                "native_g30_c2_cube_normalizer_020",
                "native_g30_c2_cube_normalizer_group_021",
            ],
        },
        {
            "theorem_id": "T030-3",
            "statement": (
                "The normalizer acts on C2^3 through an "
                "order-2 rank-1 transvection over F2. The "
                "kernel is the cube subgroup itself."
            ),
            "evidence": [
                "native_g30_c2_cube_linear_action_022",
                "native_g30_c2_cube_named_fixed_plane_023",
                "native_g30_c2_cube_involution_register_024",
            ],
        },
        {
            "theorem_id": "T030-4",
            "statement": (
                "The conjugacy orbit of the cube subgroup in "
                "Aut(G30) contains exactly 15 cubes."
            ),
            "evidence": [
                "native_g30_c2_cube_conjugacy_census_026"
            ],
        },
        {
            "theorem_id": "T030-5",
            "statement": (
                "Two cubes are adjacent when their subgroup "
                "intersection has order 4. This gives a "
                "connected quartic graph on 15 vertices, "
                "explicitly isomorphic to L(Petersen)."
            ),
            "evidence": [
                "native_g30_fifteen_cube_graph_027"
            ],
        },
        {
            "theorem_id": "T030-6",
            "statement": (
                "The 10 triangles of the cube-intersection "
                "graph are in bijection with 10 common Klein "
                "four centers having nonidentity fixed-point "
                "profile 0,0,6."
            ),
            "evidence": [
                "native_g30_cube_triangle_centers_028"
            ],
        },
        {
            "theorem_id": "T030-7",
            "statement": (
                "The 10 centers form the Petersen graph when "
                "two centers are adjacent exactly when their "
                "three-cube supports share one cube. Each of "
                "the 15 cubes is exactly one Petersen edge."
            ),
            "evidence": [
                "native_g30_petersen_from_cube_centers_029"
            ],
        },
        {
            "theorem_id": "T030-8",
            "statement": (
                "Therefore Petersen and G15=L(Petersen) are "
                "recovered intrinsically from the conjugacy and "
                "intersection geometry of affine C2^3 cube "
                "subgroups inside Aut(G30)."
            ),
            "evidence": [
                "native_g30_c2_cube_conjugacy_census_026",
                "native_g30_fifteen_cube_graph_027",
                "native_g30_cube_triangle_centers_028",
                "native_g30_petersen_from_cube_centers_029",
            ],
        },
    ]

    checks = {
        "all_source_artifacts_exist": all(
            path.exists()
            for path in SOURCE_PATHS
        ),
        "all_source_audits_pass": all(
            receipt["audit_pass"]
            for receipt in source_receipts
        ),
        "cube_group_is_c2_cubed": (
            s015["abstract_group_type"]
            == "C2_x_C2_x_C2"
        ),
        "normalizer_order_is_16": (
            s020["normalizer_order"] == 16
        ),
        "normalizer_is_d8_x_c2": (
            s021["abstract_group_type"]
            == "D8_x_C2"
        ),
        "linear_action_is_rank1_transvection": (
            s022["action_type"]
            == "rank_1_transvection_over_F2"
        ),
        "named_fixed_plane_identified": (
            s023["audit_pass"]
            and not s023[
                "fixed_plane_equals_local_triangle_klein_four"
            ]
        ),
        "seven_involution_register_complete": (
            s024["nonidentity_element_count"] == 7
        ),
        "fifteen_conjugate_cubes": (
            s026["conjugate_cube_count"] == 15
        ),
        "cube_graph_is_line_petersen": (
            s027["isomorphic_to_line_petersen"]
        ),
        "ten_common_v4_centers": (
            s028[
                "incidence3_six_fixed_involution_count"
            ]
            == 10
        ),
        "center_graph_is_petersen": (
            s029["isomorphic_to_petersen"]
        ),
        "fifteen_cubes_are_petersen_edges": all(
            row["incident_center_count"] == 2
            for row in s029["cube_edge_rows"]
        ),
    }

    payload = {
        "certificate_id": (
            "native_g30_cube_geometry_theorem_package_030"
        ),
        "title": (
            "Native affine-cube reconstruction of Petersen "
            "and G15 from G30"
        ),
        "source_receipts": source_receipts,
        "theorem_statements": theorem_statements,
        "summary_counts": {
            "aut_g30_order": 240,
            "seed_cube_order": 8,
            "seed_cube_type": "C2_x_C2_x_C2",
            "cube_normalizer_order": 16,
            "cube_normalizer_type": "D8_x_C2",
            "conjugate_cube_count": 15,
            "cube_graph_edge_count": 30,
            "cube_graph_triangle_count": 10,
            "common_v4_center_count": 10,
            "center_graph_edge_count": 15,
        },
        "reconstruction_chain": [
            "G30 automorphism action",
            "local affine cube E=C2^3",
            "15 conjugate affine cubes",
            "order-4 cube intersection graph",
            "G15 isomorphic to L(Petersen)",
            "10 common-V4 triangle centers",
            "Petersen center graph",
            "15 cubes identified as Petersen edges",
        ],
        "theorem_result": (
            "Inside Aut(G30), the local elementary abelian "
            "subgroup E=C2^3 has 15 conjugates. Their order-4 "
            "intersection graph is L(Petersen)=G15. Its 10 "
            "triangles have canonical common Klein four centers "
            "with fixed-point profile 0,0,6. Those centers form "
            "the Petersen graph, and each of the 15 cubes is "
            "exactly one Petersen edge. Thus Petersen and G15 "
            "are reconstructed intrinsically from native G30 "
            "automorphism subgroup geometry."
        ),
        "checks": checks,
        "audit_pass": all(checks.values()),
        "boundary": {
            "finite_group_theorem_package": True,
            "petersen_intrinsic_recovery": True,
            "g15_intrinsic_recovery": True,
            "native_label_alignment_open": True,
            "relation_to_g60_cube_system_open": True,
            "physical_claim": False,
        },
    }

    OUTPUT.write_text(
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )

    print("OUT ==")
    print("output:", OUTPUT)
    print("audit_pass:", payload["audit_pass"])
    print(
        "source_receipt_count:",
        len(payload["source_receipts"]),
    )
    print(
        "theorem_statement_count:",
        len(payload["theorem_statements"]),
    )
    print(
        "summary_counts:",
        payload["summary_counts"],
    )
    print(
        "theorem_result:",
        payload["theorem_result"],
    )


if __name__ == "__main__":
    main()
